name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - Elius94
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what you expected!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code
      description: Please provide a code sample that reproduces the bug
      placeholder: |
        ```js
        // Your code here
        ```
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Library Version
      description: What version of the plugin are you using?
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    id: node-version
    attributes:
      label: Node Version
      description: What version of Node.js are you using?
      placeholder: "16.6.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Windows
        - macOS
        - Ubuntu
        - Other Linux
        - Other
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Interest to fix the bug
      description: Are you interested in fixing this bug?
      options:
        - label: I would like to fix this bug!
          required: false